In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
plt.style.use('default')

In [41]:
pob = pd.read_csv('https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto1/Covid-19.csv')
pob
## Importar dataframe de casos para utilizar el dato de la población total por región.

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,...,2021-09-06,2021-09-10,2021-09-13,2021-09-17,2021-09-20,2021-09-24,2021-09-27,2021-10-01,2021-10-04,Tasa
0,Arica y Parinacota,15,Arica,15101.0,247552.0,6.0,6.0,12.0,41.0,63.0,...,29681.0,29763.0,29836.0,29929.0,30002.0,30128.0,30239.0,30376.0,30463.0,12305.7
1,Arica y Parinacota,15,Camarones,15102.0,1233.0,0.0,0.0,0.0,0.0,0.0,...,67.0,67.0,67.0,70.0,70.0,70.0,70.0,70.0,70.0,5677.2
2,Arica y Parinacota,15,General Lagos,15202.0,810.0,0.0,0.0,0.0,0.0,0.0,...,88.0,88.0,88.0,88.0,88.0,88.0,88.0,88.0,88.0,10864.2
3,Arica y Parinacota,15,Putre,15201.0,2515.0,0.0,0.0,0.0,0.0,0.0,...,204.0,205.0,207.0,208.0,207.0,211.0,215.0,213.0,213.0,8469.2
4,Arica y Parinacota,15,Desconocido Arica y Parinacota,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,156.0,158.0,163.0,161.0,163.0,165.0,165.0,167.0,170.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,Magallanes,12,Rio Verde,12103.0,211.0,0.0,0.0,0.0,0.0,0.0,...,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,8056.9
358,Magallanes,12,San Gregorio,12104.0,681.0,0.0,0.0,0.0,0.0,0.0,...,74.0,74.0,74.0,74.0,74.0,74.0,74.0,74.0,74.0,10866.4
359,Magallanes,12,Timaukel,12303.0,282.0,0.0,0.0,0.0,0.0,0.0,...,42.0,42.0,42.0,42.0,42.0,42.0,42.0,42.0,42.0,14893.6
360,Magallanes,12,Torres del Paine,12402.0,1021.0,0.0,0.0,0.0,0.0,0.0,...,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,2154.8
361,Magallanes,12,Desconocido Magallanes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.0,15.0,13.0,13.0,13.0,13.0,13.0,13.0,13.0,NaN

In [42]:
pobl = pob[['Region','Codigo region','Codigo comuna','Comuna','Poblacion']]
pobl
## Se eliminan las columnas que no se van a utilizar.

,Region,Codigo region,Codigo comuna,Comuna,Poblacion
0,Arica y Parinacota,15,15101.0,Arica,247552.0
1,Arica y Parinacota,15,15102.0,Camarones,1233.0
2,Arica y Parinacota,15,15202.0,General Lagos,810.0
3,Arica y Parinacota,15,15201.0,Putre,2515.0
4,Arica y Parinacota,15,NaN,Desconocido Arica y Parinacota,NaN
...,...,...,...,...,...
357,Magallanes,12,12103.0,Rio Verde,211.0
358,Magallanes,12,12104.0,San Gregorio,681.0
359,Magallanes,12,12303.0,Timaukel,282.0
360,Magallanes,12,12402.0,Torres del Paine,1021.0
361,Magallanes,12,NaN,Desconocido Magallanes,NaN

In [43]:
cuarentena = pd.read_csv('https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto29/Cuarentenas-Totales.csv')
cuarentena
## Importar datos sobre las fechas de cuarentena por región.

,ID,Nombre,Estado,Alcance,Fecha de Inicio,Fecha de Término,Código CUT Comuna,Detalle,Superficie en m2,Perímetro en m,Region,n_REGION
0,1,Arica,Histórica,Área Urbana Completa,2020-04-16 22:00:00,2020-05-15 22:00:00,15101,Corresponde al Radio Urbano de la Ciudad de Ar...,28050418.80,48722.30001,15,R15
1,2,Santiago Norte,Histórica,Sector Específico,2020-04-13 05:00:00,2020-05-05 22:00:00,13101,Corresponde a la extensión de la cuarentena en...,19939218.57,21599.35134,13,R13
2,3,Puente Alto Poniente,Histórica,Sector Específico,2020-04-09 22:00:00,2020-05-08 22:00:00,13201,Corresponde al sector delimitado por la Av. Co...,42364268.21,30428.05152,13,R13
3,4,El Bosque,Histórica,Comuna completa,2020-04-16 22:00:00,2020-09-21 05:00:00,13105,Aplicada a la totalidad de la comuna. Se incor...,20622713.23,18788.87075,13,R13
4,5,San Bernardo Nororiente,Histórica,Sector Específico,2020-04-16 22:00:00,2020-05-08 22:00:00,13401,Corresponde al sector delimitado por los limit...,16326216.83,24929.14572,13,R13
...,...,...,...,...,...,...,...,...,...,...,...,...
182,183,Angol,Activa,NaN,2020-12-10 05:00:00,2020-12-25 22:00:00,9201,NaN,NaN,NaN,9,R09
183,184,Cabo de Hornos,Activa,NaN,2020-12-10 05:00:00,2020-12-25 22:00:00,12201,NaN,NaN,NaN,12,R12
184,185,Los Ángeles,Activa,NaN,2020-12-12 05:00:00,2020-12-25 22:00:00,8301,NaN,NaN,NaN,8,R08
185,186,Paillaco,Histórica,NaN,2020-12-12 05:00:00,2020-12-23 05:00:00,14107,NaN,NaN,NaN,14,R14
186,187,Río Bueno,Histórica,NaN,2020-12-12 05:00:00,2020-12-23 05:00:00,14204,NaN,NaN,NaN,14,R14

In [44]:
cuarentena.drop(['Alcance','Estado','Detalle', 'Superficie en m2','Perímetro en m','n_REGION'], axis=1, inplace=True)
cuarentena
## Se eliminan los datos que no se van a utilizar.

,ID,Nombre,Fecha de Inicio,Fecha de Término,Código CUT Comuna,Region
0,1,Arica,2020-04-16 22:00:00,2020-05-15 22:00:00,15101,15
1,2,Santiago Norte,2020-04-13 05:00:00,2020-05-05 22:00:00,13101,13
2,3,Puente Alto Poniente,2020-04-09 22:00:00,2020-05-08 22:00:00,13201,13
3,4,El Bosque,2020-04-16 22:00:00,2020-09-21 05:00:00,13105,13
4,5,San Bernardo Nororiente,2020-04-16 22:00:00,2020-05-08 22:00:00,13401,13
...,...,...,...,...,...,...
182,183,Angol,2020-12-10 05:00:00,2020-12-25 22:00:00,9201,9
183,184,Cabo de Hornos,2020-12-10 05:00:00,2020-12-25 22:00:00,12201,12
184,185,Los Ángeles,2020-12-12 05:00:00,2020-12-25 22:00:00,8301,8
185,186,Paillaco,2020-12-12 05:00:00,2020-12-23 05:00:00,14107,14
186,187,Río Bueno,2020-12-12 05:00:00,2020-12-23 05:00:00,14204,14

In [45]:
cuarentena=cuarentena.rename(columns={'Código CUT Comuna':'Codigo comuna'})
cuarentena
## Se le cambia el nombre a la columna Código CUT Comuna a Codigo comuna para que tenga el mismo nombre que en el otro dataframe.

,ID,Nombre,Fecha de Inicio,Fecha de Término,Codigo comuna,Region
0,1,Arica,2020-04-16 22:00:00,2020-05-15 22:00:00,15101,15
1,2,Santiago Norte,2020-04-13 05:00:00,2020-05-05 22:00:00,13101,13
2,3,Puente Alto Poniente,2020-04-09 22:00:00,2020-05-08 22:00:00,13201,13
3,4,El Bosque,2020-04-16 22:00:00,2020-09-21 05:00:00,13105,13
4,5,San Bernardo Nororiente,2020-04-16 22:00:00,2020-05-08 22:00:00,13401,13
...,...,...,...,...,...,...
182,183,Angol,2020-12-10 05:00:00,2020-12-25 22:00:00,9201,9
183,184,Cabo de Hornos,2020-12-10 05:00:00,2020-12-25 22:00:00,12201,12
184,185,Los Ángeles,2020-12-12 05:00:00,2020-12-25 22:00:00,8301,8
185,186,Paillaco,2020-12-12 05:00:00,2020-12-23 05:00:00,14107,14
186,187,Río Bueno,2020-12-12 05:00:00,2020-12-23 05:00:00,14204,14

In [46]:
cuarentena.merge(pobl, on='Codigo comuna')
## Se combinan los dos dataframes utilizando Codigo comuna como union.

,ID,Nombre,Fecha de Inicio,Fecha de Término,Codigo comuna,Region_x,Region_y,Codigo region,Comuna,Poblacion
0,1,Arica,2020-04-16 22:00:00,2020-05-15 22:00:00,15101,15,Arica y Parinacota,15,Arica,247552.0
1,99,Arica Re-Ingreso urbano,2020-07-14 22:00:00,2020-11-09 05:00:00,15101,15,Arica y Parinacota,15,Arica,247552.0
2,2,Santiago Norte,2020-04-13 05:00:00,2020-05-05 22:00:00,13101,13,Metropolitana,13,Santiago,503147.0
3,18,Santiago,2020-03-26 21:00:00,2020-04-13 05:00:00,13101,13,Metropolitana,13,Santiago,503147.0
4,40,Santiago Extensión a Total,2020-05-05 22:00:00,2020-08-17 05:00:00,13101,13,Metropolitana,13,Santiago,503147.0
...,...,...,...,...,...,...,...,...,...,...
182,181,Arauco,2020-12-10 05:00:00,2020-12-25 22:00:00,8202,8,Biobío,8,Arauco,38679.0
183,182,Los Sauces,2020-12-10 05:00:00,2020-12-23 05:00:00,9206,9,Araucanía,9,Los Sauces,7517.0
184,185,Los Ángeles,2020-12-12 05:00:00,2020-12-25 22:00:00,8301,8,Biobío,8,Los Angeles,218515.0
185,186,Paillaco,2020-12-12 05:00:00,2020-12-23 05:00:00,14107,14,Los Ríos,14,Paillaco,20798.0
186,187,Río Bueno,2020-12-12 05:00:00,2020-12-23 05:00:00,14204,14,Los Ríos,14,Rio Bueno,32925.0

In [49]:
cuarentena['Fecha de Inicio'] = cuarentena['Fecha de Inicio'].apply(lambda x: x.split(' ')[0])
cuarentena['Fecha de Término'] = cuarentena['Fecha de Término'].apply(lambda x: x.split(' ')[0])
cuarentena
##Eliminar la hora de las fechas de inicio y término.

,ID,Nombre,Fecha de Inicio,Fecha de Término,Codigo comuna,Region
0,1,Arica,2020-04-16,2020-05-15,15101,15
1,2,Santiago Norte,2020-04-13,2020-05-05,13101,13
2,3,Puente Alto Poniente,2020-04-09,2020-05-08,13201,13
3,4,El Bosque,2020-04-16,2020-09-21,13105,13
4,5,San Bernardo Nororiente,2020-04-16,2020-05-08,13401,13
...,...,...,...,...,...,...
182,183,Angol,2020-12-10,2020-12-25,9201,9
183,184,Cabo de Hornos,2020-12-10,2020-12-25,12201,12
184,185,Los Ángeles,2020-12-12,2020-12-25,8301,8
185,186,Paillaco,2020-12-12,2020-12-23,14107,14
186,187,Río Bueno,2020-12-12,2020-12-23,14204,14